--- 
title: "PRISM Paper Analyses"
author: "Shawn Schwartz et al."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [packages.bib]
biblio-style: apalike
---

# Setup

Configure all packages, plot themes, and data directories.

## Packages
```{r}
library("here")        # for relative paths
library("fs")          # for file system operations
library("glue")        # for string concatenation
library("knitr")       # for knitting RMarkdown 
library("kableExtra")  # for making nice tables
library("showtext")    # for custom google fonts
library("nanoparquet") # for loading pupil data
library("splines")     # for spline detrending
library("pracma")      # for temporal PCA
library("factoextra")  # for PCA visualization
library("janitor")     # for cleaning column names
library("tidybayes")   # tidying up results from Bayesian models
library("brms")        # Bayesian regression models with Stan
library("patchwork")   # for making figure panels
library("broom.mixed") # for tidy lmer results
library("bayesplot")   # for visualization of Bayesian model fits 
library("modelr")      # for modeling functions
library("lme4")        # for linear mixed effects models 
library("afex")        # for ANOVAs
library("car")         # for ANOVAs
library("emmeans")     # for linear contrasts
library("ggeffects")   # for help with logistic regressions
library("parameters")  # for getting parameters
library("tidyverse")   # for wrangling, plotting, etc. 
```

## Theme
```{r}
font_add_google("Nunito", "Inter", regular.wt = 300)
showtext_auto()
showtext_opts(dpi = 300)

theme_set(
  theme_classic(base_size = 24, base_family = "Inter") +
    theme(text = element_text(size = 24))
)

opts_chunk$set(comment = "", fig.show = "hold")

options(dplyr.summarise.inform = FALSE)
options(ggplot2.discrete.color = RColorBrewer::brewer.pal(9, "Set1"))

set.seed(512)
```

## Paths
```{r}
path.output = here("data")
path.bids_base = "ses-ret_task-prism_desc-" 
path.pupil_dir = here("data", "pupil", "parquet")
```

## Global helper functions

### Calculate adjusted *d'*
```{r}
fun.dprime <- function(n_hit, n_fa, n_targets, n_distractors) {
  hit_rate_adjusted <- (n_hit + 0.5) / (n_targets + 1)
  fa_rate_adjusted <- (n_fa + 0.5) / (n_distractors + 1)
  qnorm(hit_rate_adjusted) - qnorm(fa_rate_adjusted)
}
```

### Data writer
```{r}
fun.write_block <- function(x, suffix_stem, skip_list = FALSE) {
  out_file <- path(
    path.output,
    glue("{path.bids_base}{suffix_stem}_beh.RDS")
  )

  # round to account for minor machine-level precision
  # diffs between apple silicon and x86_64 architectures
  if (!skip_list) {
    (if (is.data.frame(x)) list(x) else x) |>
      map(~ mutate(.x, across(where(is.numeric), ~ round(.x, 12)))) |>
      saveRDS(
        file = out_file,
        compress = FALSE
      ) 
  } else {
    saveRDS(
      x,
      file = out_file,
      compress = FALSE
    )
  }
}
```

```{r}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
